### ISSUE TITLE
Specify country using 'c' attribute in principal selection

### ISSUE THREAD

**Issue by martin-lindstrom** [swedenconnect/technical-framework#105]
Section 5.3.2 of [Deployment Profile for the Swedish eID Framework](https://docs.swedenconnect.se/technical-framework/updates/ELN-0602_-_Deployment_Profile_for_the_Swedish_eID_Framework.html#scoping) specifies how a SP can bypass the country selection page by using the `<saml2p:Scoping>` element. For example, the example below represents Norway:

```
<saml2p:Scoping>
  <saml2p:IDPList>
    <saml2p:IDPEntry ProviderID="http://id.swedenconnect.se/eidas/1.0/proxy-service/no" />
  </saml2p:IDPList>
</saml2p:Scoping>
```

Since we introduced the `PrincipalSelection` extension it should also be possible to add the country attribute and assign it to, for example, NO.

```
<saml2p:Extensions>
  <psc:PrincipalSelection xmlns:psc="http://id.swedenconnect.se/authn/1.0/principal-selection/ns">
    <psc:MatchValue Name="urn:oid:2.5.4.6">NO</psc:MatchValue>
  </psc:PrincipalSelection>
</saml2p:Extensions>
```

It may seem like details, but for a Signature Service that (should) set the PrincipalSelection anyway it may be a good idea to also set the `c` attribute when sending requests to the eIDAS connector. In this way the connector doesn't have to rely upon a country selection cookie to avoid displaying the country selection page.

**Comment by Razumain** [comment]
This is a great idea. But I think it can be generalised.

The signature service supporting principal selection should forward all attributes of the Signer element in the sign request as principal selection attributes. This push the decision to the SP to choose country preselection and the signature service can be quite agnostic about it.

**Comment by martin-lindstrom** [comment]
Fixed in PR https://github.com/swedenconnect/technical-framework/pull/112.
