### ISSUE TITLE
Inconsistent guidance on use of SHA-1

### ISSUE THREAD

**Issue by Razumain** [swedenconnect/technical-framework#106]
Guidance on SHA-1 is inconsistent and some text is in error.

SHA-1 should not be used as hash algorithm. Its use for other purposes should not be limited (such as use as mask generation function in RSA OAEP or RSA-PSS padding).

Guidance in section 8 states wrong standards reference (PKCS#1.5 refers to PKCS#1 version 1.5).  However this is also not correct. PKCS#1 version 1.5 has nothing to do with the SHA-1 usage, this is related to key transport using RSA-OAEP (see section 8.4)

In section 8.4, we do not ban the use of SHA-1 in the context of OAEP padding, while the recommendation in section 8 is to reject such usage.

The text in section 8.4 seems correct. Guidance in section 8 should be updated to recommend against usage of SHA-1 as digest algorithm for any purpose other than key transport in accordance with section 8.4.

**Comment by martin-lindstrom** [comment]
Already fixed.
However, fixed the RSA PKCS#1 typo in PR https://github.com/swedenconnect/technical-framework/pull/111.
