### ISSUE TITLE
Specifications for SVA tokens

### ISSUE THREAD

**Issue by Razumain** [swedenconnect/technical-framework#109]
SVA tokens (Signature Validation Assertions) will be specified as part of the technical framework.

The SVA token is used to assert the validity of one or more signatures. These signature can be validated by means of the SVA token as an alternative to validating the actual signature values.

The SVA token can be re-issued and can be used to extend the lifetime of one or more signatures far into the future. The SVA token is therefore ideal as archival signature solution.

**Comment by AndersTornqvist** [comment]
Is the “SVA tokens (Signature Validation Assertions)” defined by ETSI, CEN or OASIS? 

 

In ETSI SVA is the abbreviation for “Signature Validation Application”.

 

Hälsningar/Regards/Grüße, Anders Törnqvist, Comfact AB +46 (0)768 15 98 10

**Comment by Razumain** [comment]
Thanks Anders.

**Comment by AndersTornqvist** [comment]
How does the SVT token relate to ETSI work e.g. EN 319 102-1 & 2, TS 119 102-2 etc?

**Comment by AndersTornqvist** [comment]
It was stated that the SVT Token will be specified as part of the technical framework and that it will be used to assert the validity of one or more signatures.

We have just finished an ETSI Plugtest for validation of digital signatures in C/X/PAdES according to EN 319 102-1 & 2, TS 119 102-2 etc.

This is the way that signatures will be validated in Europe and beyond. If the SVT Token to be specified fits with and is included in the eIDAS standards, we cannot see any problem.

However, if the SVT Token is not part of the eIDAS work we foresee possible problems when implementing this and the first question is why the eIDAS work is not sufficient and can be used in Sweden when validating signatures.

**Comment by AndersTornqvist** [comment]
What requirements in the public sector does the SVT Token solve? How has these requirements been presented and substantiated by the Authorities? Are there other requirements regarding Signature Validation from Public Authorities not being addressed by the SVT Token? What is the primary requirement from Public Authorities in Sweden regarding Signature Validation?

**Comment by martin-lindstrom** [comment]
Fixed in PF https://github.com/swedenconnect/technical-framework/pull/123.
