### ISSUE TITLE
OID registry fixes and updates

### ISSUE THREAD

**Issue by Razumain** [swedenconnect/technical-framework#117]
Some issues related to the OID registry needs to be fixed and updated.

1. Change reference to E-legnamnden to swedenconnect and refer to the fan that ownership of the OID registry has been inherited by DIGG.

2. The current mod id-qcAuthConext is not used and is in conflict with RFC 7773 modules who is using the same mod OID.

3. Add the id-mod ASN.1 module identifiers from RFC 7773
    -- Sweden Connect modules        
    id-mod-auth-context-88 OBJECT IDENTIFIER ::= { id-mod 1 } - Used in RFC 7773
    id-mod-auth-context-08 OBJECT IDENTIFIER ::= { id-mod 2 } - Used in RFC 7773

5. Add the extension OID for the SVT extension

Item 5 is done to support experimental deployments of the ongoing effort to develop Signature Validation Token (SVT) specifications. Definition of this extension does not require any ANS.1 module as the extension does not contain any ASN.1 data (just the bytes of the SVT JWT token)

**Comment by martin-lindstrom** [comment]
Fixed in PR https://github.com/swedenconnect/technical-framework/pull/118
