### ISSUE TITLE
Extend DSS extension specification to allow sending several AuthnContextClassRef:s

### ISSUE THREAD

**Issue by martin-lindstrom** [swedenconnect/technical-framework#124]
Section 3.1.1 of [DSS Extension for Federated Central Signing Services](https://docs.swedenconnect.se/technical-framework/latest/09_-_DSS_Extension_for_Federated_Signing_Services.html#type-certrequestpropertiestype) states that a `saml:AuthnContextClassRef` element should be included in the `SignRequest`. The purpose of this element is to inform the IdP of which context class (level of assurance) that is required to be used during the user "authentication for signature".

This holds in all the cases when the user signs using the same eID (IdP) that was used when the user logged in to the service. However, consider the following use case:

An organization introduces federated signing but for legacy reasons keeps an old method of logging in to the service. In these cases the service needs to prompt the user which IdP to use during signing. And if this IdP supports more than one LoA-level (that are all accepted by the service), the service won't know how to assign the `saml:AuthnContextClassRef` element.
A similar use case is when signing is performed without any prior login.

To solve this issue we have to choices:

1. Extend the schema so that more than one `saml:AuthnContextClassRef` element could be passed in a `SignRequest`. This mimics the behaviour of SAML with exact matching and the signature service simply sends all received context class URI:s to the IdP (as RequestedAuthnContext:s).

2. The service does not include a `saml:AuthnContextClassRef` element in the `SignRequest`, and we change the [Implementation Profile for using OASIS DSS in Central Signing Services](https://docs.swedenconnect.se/technical-framework/latest/07_-_Implementation_Profile_for_using_DSS_in_Central_Signing_Services.html) to require that the signature service should not include any requested LoA:s in the `AuthnRequest` sent to the IdP if no `saml:AuthnContextClassRef` is received. Currently the specification states that a default LoA should be used.

Suggestion 1 is better in the sense that we have the possibility to state which LoA:s that are acceptable (one or more). However, suggestion 2 does not require any schema changes and also gives us the possibility to work in an environment/federation where authentication context classes are not used (Swamid).

My suggestion is that we implement both 1 and 2.

**Comment by per-mutzell** [comment]
I like this suggestion, it should solve several use cases out there as I can see it. Especially suggestion 1 seems important, but can understand that suggestion 2 would be useful in some setups too.
