### ISSUE TITLE
Bugfixes in SVT draft

### ISSUE THREAD

**Issue by Razumain** [swedenconnect/technical-framework#137]
A first IETF draft has been published for the SVT specification
[https://datatracker.ietf.org/doc/draft-santesson-svt](https://datatracker.ietf.org/doc/draft-santesson-svt/?include_text=1)

This draft fixes some bugs in the specification that need to bu updated here

1. Some object classes are named wrong and does not match the specification text
2. The chain_hash certificate reference concept is flawed in the current specification

The chain_hash concept is flawed since CMS provides an unordered SET of certificates, while the text demands the certificates to be hashed in exactly the order they appear in the signature. The problem here is that any code that extracts a SET of certificates from the signature, may return them in any order which may cause hash mismatch.

When writing the first draft, authors decided to change the concept and to instead hash individual certs in the validated chain with a strict order starting from the signature certificate and ending with the trust anchor cert, provided that all these certificates are present in the signature.

Finally, we should align som introductory text.

Once the IETF draft is accepted as an IETF work item, we may consider locking the draft here as version 1.0 and allow the IETF draft to evolve into version 1.1.

**Comment by AndersTornqvist** [comment]
Is it possible for you to provide us with an example of a PDF that contains an SVT Token?

 

Hälsningar/Regards/Grüße






Anders Törnqvist

+46 (0)768 15 98 10

 <https://www.comfact.se/sv-se/Kontakt/Integritetspolicy> Privacy Policy
