### ISSUE TITLE
Update of links in documents needed.

### ISSUE THREAD

**Issue by ovesemart** [swedenconnect/technical-framework#206]
På sida: https://docs.swedenconnect.se/technical-framework/Tekniska_anslutningsregler.html
Länktext: Valfrihetssystem 2017
Trasig länk: https://www.digg.se/digital-identitet/e-legitimering/offentlig-aktor/nationell-e-legitimering
Ersättningslänk? https://www.digg.se/digitala-tjanster/e-legitimering/skaffa-losningar-for-inloggning-med-e-legitimationer/erbjud-inloggning-med-svenska-e-legitimationer

På sida: https://docs.swedenconnect.se/technical-framework/Tekniska_anslutningsregler.html
Länktext: Avtal med förlitande part beträffande funktioner för elektronisk identifiering - Sweden Connect
Trasig länk: https://www.digg.se/digital-identitet/e-legitimering/offentlig-aktor/internationell-e-legitimering
Ersättningslänk? https://www.digg.se/digitala-tjanster/e-legitimering/skaffa-losningar-for-inloggning-med-e-legitimationer/erbjud-inloggning-med-utlandska-e-legitimationer

På sida: https://docs.swedenconnect.se/technical-framework/Tekniska_anslutningsregler.html
Länktext: https://www.digg.se/digital-identitet/e-legitimering/offentlig-aktor/tjanstelegitimation
Trasig länk: https://www.digg.se/digital-identitet/e-legitimering/offentlig-aktor/tjanstelegitimation
Ersättningslänk? https://www.digg.se/digitala-tjanster/e-legitimering/skaffa-losningar-for-inloggning-med-e-legitimationer/erbjud-inloggning-med-e-tjanstelegitimationer

På sida: https://docs.swedenconnect.se/technical-framework/Tekniska_anslutningsregler.html
Länktext: https://www.digg.se/digitala-tjanster/e-legitimering/e-legitimering-for-dig-som-leverantor/leverera-e-tjanstelegitimationer
Trasig länk: https://www.digg.se/digitala-tjanster/e-legitimering/e-legitimering-for-dig-som-leverantor/leverera-e-tjanstelegitimationer
Ersättningslänk? https://www.digg.se/digitala-tjanster/e-legitimering/bli-granskad-idp-leverantor alternativt
https://www.digg.se/digitala-tjanster/e-legitimering/bli-granskad-utfardare-av-svensk-e-legitimation

På sida: https://docs.swedenconnect.se/technical-framework/Tekniska_anslutningsregler.html
Länktext: tillitsnivåer
Trasig länk: https://www.digg.se/digital-identitet/e-legitimering/tillitsnivaer
Ersättningslänk: https://www.digg.se/digitala-tjanster/e-legitimering/tillitsnivaer-for-e-legitimering

På sida: https://docs.swedenconnect.se/technical-framework/Tekniska_anslutningsregler.html
Länktext: Tillitsramverk för kvalitetsmärket Svensk e-legitimation
Trasig länk: https://www.digg.se/digital-identitet/e-legitimering/tillitsnivaer/tillitsramverket
Ersättningslänk? https://www.digg.se/digitala-tjanster/e-legitimering/tillitsnivaer-for-e-legitimering/tillitsramverk-for-svensk-e-legitimation

På sida: https://docs.swedenconnect.se/technical-framework/Tekniska_anslutningsregler.html
Länktext: https://www.digg.se/digitala-tjanster/e-legitimering/e-legitimering-for-dig-som-leverantor
Trasig länk: https://www.digg.se/digitala-tjanster/e-legitimering/e-legitimering-for-dig-som-leverantor
Ersättningslänk? https://www.digg.se/digitala-tjanster/e-legitimering/bli-granskad-idp-leverantor

På sida: https://docs.swedenconnect.se/technical-framework/latest/04_-_Attribute_Specification_for_the_Swedish_eID_Framework.html
Länktext: Sambi Attributspecifikation, version 1.5
Trasig länk: https://www.sambi.se/wordpress/wp-content/uploads/2019/05/Sambi_Attributspecifikation_1.5.pdf
Http status kod: 404

På sida: https://docs.swedenconnect.se/technical-framework/latest/03_-_Registry_for_Identifiers.html
Länktext: http://id.swedenconnect.se/ap/1.0/hsaid-01´
Trasig länk: http://id.swedenconnect.se/ap/1.0/hsaid-01´
Http status kod: java.net.UnknownHostException: id.swedenconnect.se
Kommentar: Inget fel på url, den är dock inlagd i dokumentet som href och inte som <code> på två ställen

På sida: https://docs.swedenconnect.se/technical-framework/updates/04_-_Attribute_Specification_for_the_Swedish_eID_Framework.html
Länktext: Sambi Attributspecifikation
Trasig länk: https://www.sambi.se/attributes/
Http status kod: 404

På sida: https://docs.swedenconnect.se/technical-framework/latest/09_-_DSS_Extension_for_Federated_Signing_Services.html
Länktext: W3C-CHAR
Trasig länk: https://www.w3.org/TR/WD-charreq/
Http status kod: 404

På sida: http://docs.swedenconnect.se/technical-framework/latest/06_-_Entity_Categories_for_the_Swedish_eID_Framework.html
Länktext: EidAttributes
Trasig länk: http://docs.swedenconnect.se/technical-framework/latest/eidattributes
Http status kod: 404
Kommentar! Några internlänkningar av EidAttributes saknar # före länk (href="#eidattributes"), därav trasig länk på sidan.

På sida: http://docs.swedenconnect.se/technical-framework/latest/06_-_Entity_Categories_for_the_Swedish_eID_Framework.html
Länktext: Tillitsramverket för Svensk e-legitimation.
Trasig länk: https://www.digg.se/digital-identitet/e-legitimering/tillitsnivaer/tillitsramverket
Ersättningslänk? https://www.digg.se/digitala-tjanster/e-legitimering/tillitsnivaer-for-e-legitimering/tillitsramverk-for-svensk-e-legitimation

På sida: http://docs.swedenconnect.se/technical-framework/latest/14_-_Principal_Selection_in_SAML_Authentication_Requests.html
Länktext: EidAttributes
Trasig länk: http://docs.swedenconnect.se/technical-framework/latest/eidattributes
Kommentar! EidAttributes saknar # före länk (href="#eidattributes"), därav trasig länk på sidan.

**Comment by martin-lindstrom** [comment]
Fixed the broken links in "Tekniska anslutningsregler". Digg had restructured their site and never bothered with redirects. Odd.
