### ISSUE TITLE
Update signing specifications

### ISSUE THREAD

**Issue by Razumain** [swedenconnect/technical-framework#69]
Two new proposals to store transaction related evidence in signing certificates.

- Store transaction identifier as subject attribute: 1.2.752.201.3.2 with a mapping to the SAML attribute in AuthContext extension

- Store the SAD payload in the AuthnContext extension

**Comment by Razumain** [comment]
No. The Assertion is fine as it is. This is about placing the sad payload in the certificate as extra evidence that the SAP process was implemented. The RFC 7773 allows multiple payloads to be stored that provides info about the auth context:

AuthenticationContext ::= SEQUENCE {
     contextType     UTF8String,
     contextInfo     UTF8String OPTIONAL
 }

**Comment by AndersTornqvist** [comment]
Can you elaborate on the purpose and justification of the proposals? 

 

Hälsningar/Regards/Grüße, Anders Törnqvist, Comfact AB +46 (0)768 15 98 10

**Comment by martin-lindstrom** [comment]
@Razumain By introducing the `<sacex:ExtAuthInfo>` element to be used in the `<saci:AuthContextInfo>` we can store any attribute there - both transactionID and SAD...

**Comment by martin-lindstrom** [comment]
Fixed in PR https://github.com/swedenconnect/technical-framework/pull/116/
