### ISSUE TITLE
Nit in Deployment profile 6.1: Inconsistent requirement language for encrypted assertions

### ISSUE THREAD

**Issue by Razumain** [swedenconnect/technical-framework#71]
The following text:

Identity Providers SHALL utilize XML Encryption and return a <saml2:EncryptedAssertion> element in the <saml2p:Response> message. The elements <saml2:EncryptedID> and <saml2:EncryptedAttribute> MUST NOT be used; instead the entire assertion should be encrypted.

In the end. Change "should be encrypted" to "MUST be encrypted".

Reason:
There is a slight risk that someone may interpret "should" as if this is only recommended.

**Comment by martin-lindstrom** [comment]
Fixed in PR https://github.com/swedenconnect/technical-framework/pull/77.
