### ISSUE TITLE
Ensuring SignMessage is only displayed to intended user

### ISSUE THREAD

**Issue by martin-lindstrom** [swedenconnect/technical-framework#99]
Originally, the `PrincipalSelection` extension was intended to aid the user experience. When an SP send along the personal identity number in the `PrincipalSelection` extension an IdP that normally prompts for this ID could deliver a more lean user experience.

However, in some cases the SP may have different requirements. Suppose that a signature service SP wants to ensure that the signature message is only displayed to a specific user (and nonone else). The signature service could then pass along this identity in the `PrincipalSelection` extension and implicitly say to the IdP. Don't prompt for the user ID (if the IdP usually does this) **and** make sure that only the indicated user sees the sign message.

For the eIDAS connector (that doesn't prompt) for a user ID, but displays the sign message for approval after it knows the identity this could easily be implemented. It simply should check that the identity received in the `PrincipalSelection` extension corresponds with the attributes received from the foreign IdP before displaying the sign message.

For other IdP:s, such as BankID and Freja, that prompts for the user ID **and** displays the signature message as part of the authentication (well, signature to be correct), we could state that no prompting of personal identity number MUST be done if the personal identity number is passed in the `PrincipalSelection` extension. This ensures that the BankID/Freja apps are initiated using the received personal identity number.

On top of this we could also introduce a new SAML status code: `http://id.swedenconnect.se/status/1.0/unexpectedPrincipal` to be used in the cases where an authenticated user's identity does not match the contents of `PrincipalSelection`.

> SAML Core defines `urn:oasis:names:tc:SAML:2.0:status:UnknownPrincipal` that has the meaning: "_The responding provider does not recognize the principal specified or implied by the request._".
> I',m not sure that it is a good idea to use that since the user isn't unknown. The user's identity doesn't match what we want or expected.

Thoughts?

**Comment by maganvill** [comment]
The suggestion seems reasonable. 

I only have one concern regarding signing with Telia even though the volumes are almost negligible. 

The browser plugin Net iD has no means to display sign message. And letting the user first sign using Net iD and then see the sign message in browser feels backward. That could be solved by first authenticate the user but would of course require both authentication and signing. 

I.e. a minor drawback affecting not many persons

**Comment by maganvill** [comment]
What are the changes of someone else get to read the sign message than the intended user? 

In practice the browser (session) needs to be transferred to someone else by theafth or with intent e.g. leaving the chair...

**Comment by martin-lindstrom** [comment]
I don't know whether we should specify something regarding Telia. Maybe it is best that we make sure that the generic requirements of the eID Framework applies. And that's it.

> What are the changes of someone else get to read the sign message than the intended user?

I guess that you mean "chances". Well this may happen if the IdP doesn't handle the PrincipalSelection extension (and doesn't have the user ID saved in a cookie). In those cases the IdP prompts for the userID to use, and that may differ from what the signature service expects.

**Comment by maganvill** [comment]
> In those cases the IdP prompts for the userID to use, and that may differ from what the signature service expects.

Exactly, I tried to elaborate why a user would enter a different userID.

**Comment by martin-lindstrom** [comment]
There aren't any cases (I guess) where a user would do that on purpose. But it may happen, deliberately or as part of fraudulent behaviour. And it is the IdP:s responsibility to only show the sign message to the intended user.

**Comment by vedrnes** [comment]
Just to clarify, would you expect the IdP to return http://id.swedenconnect.se/status/1.0/unexpectedPrincipal if the principal that signed does not match PrincipalSelection? If so, how does this help in preserving privacy of the sign message, i.e not showing the sign message to the wrong user?

**Comment by GunnarKlintberg** [comment]
As I see it this probably are most likely happens in the cross-border use case for end users that do not have static ID's as we have in Sweden.  
In general, I do not see any reason why the solution shall allow Change eID (Ie IDP) in the case an end user has logon to the e-service and Agree to sign, and in step two use another Idp when they do the Authentication for signing.  
Why allow to logon with BankID and that in the Authentication for signing use Freja eID+?
In the Swedish Federation we shall both by policy and technical implementation block this possibility is my opinion. 
By the PrincipalSelection we implement a standard way of implemented the automation we look for from an end user point of view. 

But in the eIDAS use case the Swedish node cannot forbid the end user to do that because we do not have that control as we have in the technical federation of Sweden Connect and the federation Policy. 
My suggestion is here that as Martin’s suggestion to implement specially in the eIDAS node this new Status that can be returned to the e-service IF the IdP detect this mismatch.

**Comment by martin-lindstrom** [comment]
> Just to clarify, would you expect the IdP to return http://id.swedenconnect.se/status/1.0/unexpectedPrincipal if the principal that signed does not match PrincipalSelection? If so, how does this help in preserving privacy of the sign message, i.e not showing the sign message to the wrong user?

The unexpectedPrincipal status code only makes sense for the connector since the eIDAS node lets the user authenticate before displaying the sign message. In other cases (BankID/Freja) we know that only the intended user sees the sign message as long as the IdP uses the personal identity number found in the PrincipalSelection extension.

**Comment by martin-lindstrom** [comment]
Then there are other use cases for non-signature cases. If the SP sends a PrincipalSelection holding an ID and another user is authenticated. In those cases the IdP MAY respond with an unexpected user error. We don't want to enforce this with SHOULD or MUST since it's the SP responsibility to check that it got what it expected.

**Comment by martin-lindstrom** [comment]
I'll think we make use of the `urn:oasis:names:tc:SAML:2.0:status:UnknownPrincipal` core SAML code for the cases discussed above. Everytime we deviate from core SAML we move a bit further away from the "should be able to use shelf-products" principle.

**Comment by martin-lindstrom** [comment]
Se PR https://github.com/swedenconnect/technical-framework/pull/104.
